# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/production.key
        chmod 600 ~/.ssh/production.key
        cat >>~/.ssh/config <<END
        Host production
          HostName $SSH_HOST
          User $SSH_USER
          Port 2220
          IdentityFile ~/.ssh/production.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
        SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
        SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
    - run: npm ci
    - run: set PUBLIC_URL=https://notes.jleo.tech && set REACT_APP_API_ROOT_URL=https://notes.jleo.tech && npm run build --if-present
    - name: Clean previous version
      run: ssh production "rm -Rf /opt/containers/nginx/data/nginx/html/notes/*"
    - name: Copy new version
      run: scp -r build/* production:/opt/containers/nginx/data/nginx/html/notes/
    - name: Reload NGINX
      run: ssh production "cd /opt/containers/nginx && ./reload.sh"
